security:
  ignored: /favicon.ico, /
  basic:
    enabled: false
idServiceUrl: ${ID_SERVICE_URL}
spring.oauth2:
    client:
      accessTokenUri: ${ID_SERVICE_URL}/oauth/token
      userAuthorizationUri: ${ID_SERVICE_URL}/oauth/authorize
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
    resource:
      jwt.keyUri: ${ID_SERVICE_URL}/token_key